# Generated by Django 6.1.1 on 2026-10-08 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.MinValueValidator(11)]),
        ),
    ]
