# Generated by Django 6.1.1 on 2026-10-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
    ]
