# Generated by Django 6.1.1 on 2026-10-08 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.links'),
        ),
    ]
