# Generated by Django 6.1.1 on 2026-10-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_project_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.links'),
        ),
    ]
