# Generated by Django 6.1.1 on 2026-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_hero_alter_project_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLnks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Social media links',
                'verbose_name_plural': 'Social media links',
            },
        ),
    ]
