# Generated by Django 6.1.1 on 2026-10-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_sociallnks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLnks',
            new_name='SocialLinks',
        ),
    ]
