# Generated by Django 6.1.1 on 2026-10-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_sociallnks_sociallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='odoo_modules',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.DeleteModel(
            name='OdooModule',
        ),
        migrations.AddField(
            model_name='project',
            name='odoo_modules',
            field=models.CharField(default='', max_length=100),
        ),
    ]
