# Generated by Django 6.1.1 on 2026-10-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_project_odoo_modules_remove_skill_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
