# Generated by Django 6.1.1 on 2026-10-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_delete_certification_remove_skill_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cv',
        ),
    ]
